apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 14.6.6
    helm:
      values: |
        global:
          security:
            allowInsecureImages: true
        image:
          registry: docker.io
          repository: bitnamilegacy/rabbitmq
          tag: 3.13.6-debian-12-r1
        volumePermissions:
          enabled: false
          image:
            registry: docker.io
            repository: bitnamilegacy/os-shell
        auth:
          username: rabbitmq
          password: rabbitmq
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: rabbitmq.local
          pathType: Prefix
          path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true