apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer
  namespace: portal
spec:
  ingressClassName: nginx
  rules:
    - host: portal.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homer
                port:
                  number: 80
